package com.cashflow.ai.presentation.theme

import androidx.compose.ui.graphics.Color

// Light Scheme Colors (PRD Specification)
val md_theme_light_primary = Color(0xFF006A6A)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF7DF1F1)
val md_theme_light_onPrimaryContainer = Color(0xFF001F1F)
val md_theme_light_secondary = Color(0xFF4A6363)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFCDE8E8)
val md_theme_light_onSecondaryContainer = Color(0xFF051F1F)
val md_theme_light_tertiary = Color(0xFF525C7D)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFDFE0FF)
val md_theme_light_onTertiaryContainer = Color(0xFF0E1935)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFBFCFC)
val md_theme_light_onBackground = Color(0xFF191C1C)
val md_theme_light_surface = Color(0xFFFBFCFC)
val md_theme_light_onSurface = Color(0xFF191C1C)
val md_theme_light_surfaceVariant = Color(0xFFDBE4E4)
val md_theme_light_onSurfaceVariant = Color(0xFF3F4848)
val md_theme_light_outline = Color(0xFF6F7979)

// Dark Scheme Colors
val md_theme_dark_primary = Color(0xFF5FDBDB)
val md_theme_dark_onPrimary = Color(0xFF003737)
val md_theme_dark_primaryContainer = Color(0xFF004F4F)
val md_theme_dark_onPrimaryContainer = Color(0xFF7DF1F1)
val md_theme_dark_secondary = Color(0xFFB1CCCC)
val md_theme_dark_onSecondary = Color(0xFF1B3535)
val md_theme_dark_secondaryContainer = Color(0xFF324B4B)
val md_theme_dark_onSecondaryContainer = Color(0xFFCDE8E8)
val md_theme_dark_tertiary = Color(0xFFBAC8EB)
val md_theme_dark_onTertiary = Color(0xFF24304D)
val md_theme_dark_tertiaryContainer = Color(0xFF3B4664)
val md_theme_dark_onTertiaryContainer = Color(0xFFDFE0FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF191C1C)
val md_theme_dark_onBackground = Color(0xFFE0E3E3)
val md_theme_dark_surface = Color(0xFF191C1C)
val md_theme_dark_onSurface = Color(0xFFE0E3E3)
val md_theme_dark_surfaceVariant = Color(0xFF3F4848)
val md_theme_dark_onSurfaceVariant = Color(0xFFBFC8C8)
val md_theme_dark_outline = Color(0xFF899393)

// Financial semantic colors
val IncomeGreen = Color(0xFF2E7D32)
val IncomeGreenLight = Color(0xFFE8F5E9)
val ExpenseRed = Color(0xFFC62828)
val ExpenseRedLight = Color(0xFFFFEBEE)

// AI Confidence semantic colors
val ConfidenceHighColor = Color(0xFF2E7D32)
val ConfidenceMediumColor = Color(0xFFF57F17)
val ConfidenceLowColor = Color(0xFFC62828)
